# Generated by Django 4.1.5 on 2023-02-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestdataapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book',
        ),
    ]
